# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'node-10':
    docker:
      - image: circleci/node:10
    working_directory: ~/typo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - ~/.cache/npm
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run test

  'node-latest':
    docker:
      - image: circleci/node:latest
    working_directory: ~/typo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - ~/.cache/npm
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run test

workflows:
  version: 2
  build:
    jobs:
      - 'node-10'
      - 'node-latest'
